import { readdir, readFile, stat } from 'fs/promises'
import { join, resolve } from 'path'
import { cwd } from 'process'
import env from '@/helpers/env'
import logger from '@/lib/logger'
import { useYtdlpForYoutube } from '@/services/youtubeBackend'

let loggedPath: string | undefined
let cookiePool: string[] | undefined
let poolResolved = false

export function shouldUseYoutubeCookies(): boolean {
  return env.YOUTUBE_USE_COOKIES
}

export function shouldLoadYoutubeCookiePool(): boolean {
  if (!useYtdlpForYoutube()) {
    return false
  }
  return shouldUseYoutubeCookies() || env.YOUTUBE_FALLBACK_COOKIES
}

export function isYoutubeCookiesInvalid(message: string): boolean {
  const m = message.toLowerCase()
  return (
    m.includes('cookies are no longer valid') ||
    m.includes('likely been rotated') ||
    m.includes('account cookies are no longer valid')
  )
}

export function isYoutubeBotBlock(message: string): boolean {
  const m = message.toLowerCase()
  return (
    isYoutubeCookiesInvalid(m) ||
    m.includes('sign in to confirm') ||
    m.includes("you're not a bot") ||
    m.includes('not a bot') ||
    m.includes('login_required') ||
    m.includes('cookies-from-browser')
  )
}

function isCookiePathError(message: string): boolean {
  const m = message.toLowerCase()
  return m.includes('is a directory') && m.includes('cookie')
}

export function isCookieConfigurationError(message: string): boolean {
  return isCookiePathError(message)
}

async function isCookiesFile(filePath: string): Promise<boolean> {
  try {
    const info = await stat(filePath)
    return info.isFile()
  } catch {
    return false
  }
}

async function inspectCookiesFile(filePath: string): Promise<void> {
  try {
    const sample = (await readFile(filePath, 'utf8')).slice(0, 4000)
    const ytDlpExportHeader = /^#.*generated by yt-dlp/m.test(sample)
    const hasSession = /LOGIN_INFO|SAPISID|SID\t|__Secure-1PSID/i.test(sample)
    if (ytDlpExportHeader && !hasSession) {
      logger.warn(
        'cookies.txt was exported by yt-dlp itself — re-export from browser. See docs/YOUTUBE-COOKIES.md'
      )
    }
    if (!hasSession) {
      logger.warn(
        'cookies.txt may be incomplete (no LOGIN_INFO/SAPISID) — re-export from Chrome'
      )
    }
  } catch {
    // ignore
  }
}

async function tryPath(filePath: string): Promise<string | undefined> {
  if (!(await isCookiesFile(filePath))) {
    return undefined
  }
  if (loggedPath !== filePath) {
    loggedPath = filePath
    logger.info('yt-dlp cookies file', { path: filePath })
    await inspectCookiesFile(filePath)
  }
  return filePath
}

async function tryCookieDirectory(dirPath: string): Promise<string | undefined> {
  try {
    const info = await stat(dirPath)
    if (!info.isDirectory()) {
      return undefined
    }
  } catch {
    return undefined
  }
  const innerNames = [
    'cookies.txt',
    'youtube.txt',
    'www.youtube.com_cookies.txt',
    'cookie.txt',
  ]
  for (const name of innerNames) {
    const inner = join(dirPath, name)
    const found = await tryPath(inner)
    if (found) {
      return found
    }
  }
  logger.error('cookie is a directory, not a file — use cookies-pool/ or cookies.txt', {
    path: dirPath,
  })
  return undefined
}

async function listCookiePoolDir(dirPath: string): Promise<string[]> {
  try {
    const info = await stat(dirPath)
    if (!info.isDirectory()) {
      return []
    }
    const names = await readdir(dirPath)
    const files: string[] = []
    for (const name of names.sort()) {
      if (!name.endsWith('.txt')) {
        continue
      }
      const full = join(dirPath, name)
      if (await isCookiesFile(full)) {
        files.push(full)
      }
    }
    return files
  } catch {
    return []
  }
}

/** Load admin cookie file(s) when cookies-first or fallback mode is enabled. */
export async function resolveCookiePool(): Promise<string[]> {
  if (!shouldLoadYoutubeCookiePool()) {
    return []
  }
  if (poolResolved) {
    return cookiePool ?? []
  }
  poolResolved = true
  const root = cwd()
  const poolDir = env.YOUTUBE_COOKIE_POOL_DIR_RESOLVED ?? resolve(root, 'cookies-pool')
  const fromPool = await listCookiePoolDir(poolDir)
  if (fromPool.length > 0) {
    cookiePool = fromPool
    logger.info('YouTube cookie pool', { count: fromPool.length, dir: poolDir })
    return fromPool
  }

  const single = await resolveCookiesPath()
  cookiePool = single ? [single] : []
  if (cookiePool.length === 0) {
    logger.warn('YOUTUBE_USE_COOKIES=true but no cookies.txt or cookies-pool/*.txt found')
  }
  return cookiePool
}

export function pickCookieForJob(jobId: string): string | undefined {
  const pool = cookiePool
  if (!pool?.length) {
    return undefined
  }
  const idx = parseInt(jobId.slice(-8), 16) % pool.length
  return pool[idx]
}

export function cookiePoolSize(): number {
  return cookiePool?.length ?? 0
}

export async function resolveCookiesPath(): Promise<string | undefined> {
  const root = cwd()
  const candidates = [
    env.COOKIES_PATH_RESOLVED,
    resolve(root, 'cookies.txt'),
    resolve(root, 'cookie.txt'),
    resolve(root, 'cookie'),
  ].filter((p): p is string => Boolean(p))

  for (const filePath of candidates) {
    const asFile = await tryPath(filePath)
    if (asFile) {
      return asFile
    }
    const fromDir = await tryCookieDirectory(filePath)
    if (fromDir) {
      return fromDir
    }
  }

  return undefined
}
