#!/bin/bash
# Test YouTube download on Hostinger (cookies + Node for yt-dlp EJS)
set -e
cd "$(dirname "$0")/.."

chmod +x bin/yt-dlp 2>/dev/null || true

if [ ! -f cookies.txt ]; then
  echo "ERROR: cookies.txt missing in $(pwd)"
  exit 1
fi

if head -3 cookies.txt | grep -q 'generated by yt-dlp'; then
  echo "WARNING: cookies.txt looks like yt-dlp export — use browser extension instead"
fi

NODE=""
for candidate in \
  "${YTDLP_NODE_PATH:-}" \
  /opt/alt/alt-nodejs22/root/usr/bin/node \
  /opt/alt/alt-nodejs20/root/usr/bin/node \
  /opt/alt/alt-nodejs18/root/usr/bin/node; do
  [ -z "$candidate" ] && continue
  if [ -x "$candidate" ]; then
    if "$candidate" --version >/dev/null 2>&1; then
      NODE="$candidate"
      break
    fi
  fi
done

if [ -z "$NODE" ]; then
  echo "ERROR: Node not found. Try: ls /opt/alt/alt-nodejs*/root/usr/bin/node"
  exit 1
fi

echo "Using Node: $NODE"
echo "Using cookies: $(pwd)/cookies.txt"
echo "Running yt-dlp test download..."

rm -f test.mp4

./bin/yt-dlp \
  --cookies ./cookies.txt \
  --js-runtimes "node:$NODE" \
  -f "best[ext=mp4]/best" \
  -o test.mp4 \
  "https://www.youtube.com/watch?v=zSH15dIl7D0"

ls -lh test.mp4
echo "OK: test.mp4 downloaded"
